version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - graphql-auth

  graphql:
    build: .
    container_name: graphql
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - graphql-auth

networks:
  graphql-auth:

volumes:
  mongodb: